# This file is the main config file for your service.

service: rekognize-image-serverless-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: ap-northeast-2

resources:
  Resources:
    IamRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: RekognizeImageRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: RekognizeImagePolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - rekognition:DetectLabels
                  Resource: "*"
                - Effect: Allow
                  Action:
                    - s3:GetObject
                  Resource:
                    - "arn:aws:s3:::rekognize-images-31-10-2023-mayflower-bucket/*"
                - Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:CreateLogGroup
                    - logs:PutLogEvents
                  Resource: 
                       - Fn::Sub: "arn:aws:logs:*:*:*"
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource: 
                    - "arn:aws:lambda:*:*:function/RekognizeImageAppFunc"


functions:
  RekognizeImageFunc:
    handler: handler.lambda_handler
    events:
      - s3:
          bucket: rekognize-images-31-10-2023-mayflower-bucket
          event: s3:ObjectCreated:Put
    role: 
      Fn::GetAtt:
        - IamRole
        - Arn
    environment:
      AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
      LOG_GROUP_NAME: /aws/lambda/RekognizeImageAppFunc

